name: PR Merged Notification

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Post merge comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" \
        -X POST \
        -d '{"body":"This PR has been merged! Thank you for your contribution. 🎉"}' \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
